### ISSUE TITLE
Image Upload Buttons Not Aligned

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/vue-form-builder#118]
<img width="347" alt="Screenshot 2019-03-14 13 31 20" src="https://user-images.githubusercontent.com/535300/54389569-9f4c6e80-465d-11e9-971b-7d1d72093313.png">

**Comment by danloa** [comment]
@velkymx  The problem is reproduced in the server http://develop.bpm4.qa.processmaker.net/ In local enviroment and using Chrome and Firefox the problem is not observed. Can it be a problem with develop not updated?

**Comment by velkymx** [comment]
This seems to be resolved
