### ISSUE TITLE
CSS Name

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/vue-form-builder#135]
We'd like to add an optional field to the inspector for ALL controls. This field will be called css-name and will add a custom attribute to the div container that can be referenced by the custom css. If the css-name is not blank it will get added and can be referenced by [css-name="name"] in the custom css

**Comment by tdondich** [comment]
Note, the attribute is called 'selector', and not 'css-name' to avoid the dash which causes confusion and is more generic where the selector could potentially be used by other things.
