### ISSUE TITLE
add name and value to submit button

### ISSUE THREAD

**Issue by milaendo** [ProcessMaker/vue-form-builder#23]
The submit button should have a name and value so it can be used as "approve or reject" buttons

**Comment by velkymx** [comment]
When a button is clicked, it should add a value, in this case, approved and it should contain a value (1 for approved or 0 for declined) to the data object.

![screenshot 2018-12-05 09 17 13](https://user-images.githubusercontent.com/535300/49531311-e660e180-f86e-11e8-9703-c02d150d15c7.png)
