### ISSUE TITLE
Inspector Bug

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/vue-form-builder#35]
If you switch between 2 text boxes, the text content in the inspector will not refresh, but rather keep displaying data from the first text box. When you interact with the inspector, the values for the second text box will be overridden with those from the first. In order to effectively edit properties for a 2nd text box, you need to select another (non text box) element first, and then the inspector will update properly.

Steps to Reproduce

1. Drag a text box into the screen. 
2. Drag a second text box into the screen. 
3. Select the first text box and add some text content in the Inspector pane. 
4. Select the second text box. Notice the text content property did not refresh and still reads the content for the first box. 
5. Select the text content box and add a character or space. notice how the entire content of the second box is now updated to reflect what was both the content for boxes 1 and 2. 
6. Drag a line input into the screen. 
7. select one of the text boxes and then other. notice again how the content does not refresh. 
8. Select the input box and then the text box. notice how when selecting the text box after the input box refreshes its content properly.

**Comment by marcoAntonioNina** [comment]
is solved with https://github.com/ProcessMaker/vue-form-elements/issues/12
