### ISSUE TITLE
Red delete X is always in top right for all components

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/vue-form-builder#67]
Mentioned here: https://github.com/ProcessMaker/bpm/pull/1384#issuecomment-465283401

A bug in the CSS put the delete X in the top right corner, overlapping other delete Xs

**Comment by velkymx** [comment]
This isn't in the sprint... https://github.com/ProcessMaker/bpm/milestone/33

**Comment by nolanpro** [comment]
This will be fixed as part of https://github.com/ProcessMaker/vue-form-builder/pull/91
