### ISSUE TITLE
Add Inspector Accordian Groups

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/vue-form-builder#69]
I want to be able to group elements in the inspector sidebar on right. Group name, icon and id, by default only open the configuration "tab".

<img alt="screenshot 2019-02-12 08 13 57" width="214" src="https://user-images.githubusercontent.com/535300/52649965-27dcc100-2e9e-11e9-8af8-10d7972f2e28.png">

https://github.com/ProcessMaker/modeler/issues/221

**Comment by velkymx** [comment]
Make this a form element. https://github.com/ProcessMaker/vue-form-elements/issues/21

**Comment by chipit24** [comment]
Issue resolved: https://github.com/ProcessMaker/vue-form-elements/issues/21.
