### ISSUE TITLE
Inputs Not Responding

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/vue-form-builder#72]
When I set a value of an input specifically it is not picking up the responsive value from the json data.

**Comment by caleeli** [comment]
Looks like it is working:
![inputJsonData](https://user-images.githubusercontent.com/8028650/54364082-94d0ab80-4642-11e9-8239-db3400cc1569.gif)

**Comment by velkymx** [comment]
Great. I wonder if this was just broken before we had to roll it all back.
